- name: demo on variables
  hosts: all
  vars:
    
    URL: play.google.com

  tasks:
    
    - name: printing the url
      ansible.builtin.debug:
        msg: the url is {{ URL }}

    - name: printing the url
      ansible.builtin.debug:
        msg: "{{ URL }}"

      vars:
        URL: text.google.com

    - name: printing the url from CLI
      ansible.builtin.debug:
        msg: URL_CLI is {{ URL_CLI }}


