- name: demo on variables
  hosts: all
  vars:
    URL: play.google.com

  tasks:
    
    - name: printing the url
      ansible.builtin.debug:
        msg: the url is "{{URL}}"


- name: demo on variables 
  hosts: all  # all is default group in inventory file which includes everything 
  vars:       # Global varibale
      URL: play.google.com 
  # vars_prompt:
  #     - name: URL 
  #       prompt: Enter URL  
  #       private: no
  tasks: 
    - name: pritning URL  
      ansible.builtin.debug:
        msg: Url that we print is {{ URL }}  