- name: demo on variables
  hosts: all
  vars:
    
    URL: play.google.com

  vars_files:
      - dev-vars.yml

  tasks:
    
    - name: printing the url
      ansible.builtin.debug:
        msg: the url is {{ URL }}

    - name: printing the url
      ansible.builtin.debug:
        msg: "{{ URL }}"

      vars:
        URL: text.google.com

  
    - name: Printing URL from CLI 
      ansible.builtin.debug:
        msg: URL_CLI is {{ CLI_URL }} 

        # CLI Variable > local variable > > files_variables>  global variable